### PR TITLE
Make compilation with GBL v04 possible

### LINKED ISSUE #28: aidaTT doesn't compile with v4 of GeneralBrokenLines
In v4 of GeneralBrokenLines:
- `GblPoint` and `GblTrajectory` now use pure Eigen matrices instead of ROOT's TMatrixD/TVectorD in `GBLInterface.cc`
- `MilleBinary` has been replaced by `Mille::MilleRecord` hierarchy
so, for now, the Key4hep stack stays in V02-02-01 for GeneralBrokenLines.

The patch that would be needed to make it work could start with (I didn't get it to compile):
``` diff
--- fittingAlgorithms/include/GBLInterface.hh.orig
+++ fittingAlgorithms/include/GBLInterface.hh
@@ -12,7 +12,7 @@
 
 // GBL:
 #include "GblTrajectory.h"
-#include "MilleBinary.h"
+#include "Mille/MilleRecordC.h"
 
 
 /* This is an interface class to the general broken lines package by C. Kleinwort.
@@ -97,7 +97,7 @@
     
     mutable ResMap _theResults{};
 
-    gbl::MilleBinary* _milleBinary {};
+    Mille::MilleRecordC* _milleBinary {};
 
   };
 
--- fittingAlgorithms/src/GBLInterface.cc.orig
+++ fittingAlgorithms/src/GBLInterface.cc
@@ -9,7 +9,7 @@
 {
   GBLInterface::GBLInterface() : _trajectory(NULL), _correctionVector(NULL), _covarianceMatrix(NULL)
   {
-    _milleBinary = new gbl::MilleBinary() ;
+    _milleBinary = new Mille::MilleRecordC() ;
   }
 
 
@@ -210,7 +210,7 @@
 
 
 
-     _trajectory->milleOut ( *_milleBinary ) ;
+     _trajectory->milleOut ( _milleBinary ) ;
 
     //_trajectory->printTrajectory(100) ;
     //_trajectory->printPoints(100) ;
--- CMakeLists.txt.orig
+++ CMakeLists.txt
@@ -84,6 +84,7 @@
     MESSAGE( STATUS "Doxygen not installed or found -- API documentation can't be generated!" )
 ENDIF(DOXYGEN_FOUND)
 
+TARGET_LINK_LIBRARIES( ${PROJECT_NAME} -L${GBL_LIBRARY_DIRS} Mille2 )
 IF( GBL_FOUND )
         ADD_DEFINITIONS( "-DUSE_GBL" )
         ADD_DEFINITIONS( "-DGBL_EIGEN_SUPPORT_ROOT" )
```

### PR DESCRIPTION
**Pull request by jmcarcell**
BEGINRELEASENOTES
- Make compilation with GBL v04 possible. Headers have been moved and `MilleBinary` doesn't exist anymore. These changes keep compilation working for GBL v02 (what we are using right now).

ENDRELEASENOTES

I ran the CLD reconstruction with GBL v02 and GBL v04 and the results are the same.
Fix #28.

### CODE REVIEW

**Comment by jmcarcell** [comment]
Review needed from someone with merge powers @andresailer @tmadlener @gaede.

File: fittingAlgorithms/src/GBLInterface.cc [hunk 1]
```diff
@@ -1,15 +1,21 @@
 #ifdef USE_GBL
 #include "GBLInterface.hh"
 #include "utilities.hh"
-//#include "MilleBinary.h"
+#ifdef GBL_V04
+#include "Mille/MilleRecordC.h"
+#endif
```
Comment (andresailer) [inline fittingAlgorithms/src/GBLInterface.cc]:
```suggestion
```
Not needed, as this comes from The GBLInterface.hh at the same time as GBL_V04 is defined. (or drop that include there if not needed in the header?)

Comment (jmcarcell) [reply fittingAlgorithms/src/GBLInterface.cc]: Removed and confirmed that it builds.

**Comment by jmcarcell** [comment]
Happy with this?
